using lplplp.Models;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Text;
using System.Threading.Tasks;

namespace lplplp.ViewModel
{
    class KunstværkerViewModel : INotifyPropertyChanged
    {
        #region Konstanter
        private const string Laila = "Laila Westergaard (født 1964) er uddannet på Det Jyske Kunstakademi 1985-89 og på Guzel Sanatlar Falkutesi i Istanbul 1989-90. Hun debuterede på Kunstnernes Efterårsudstilling i 1988 og har siden haft talrige udstillinger i ind- og udland. Hun har modtaget flere legater og udført en lang række udsmykninger både i offentlig og privat regi. Laila Westergaard er medlem af kunstnersammenslutningen Den Gyldne.";
        private const string GranitBænke = "Med et længere ophold i Istanbul bag sig, har Laila Westergaard ønsket at forlene sin opgave for udsmyk-ningen af RO’s Torv, bænke til centergangene, med lidt af den stemning af fest og leg, der omgiver handelen i de tyrkiske basarer. De 14 bænke, der hver måler 180 x 45 centimeter og er 47 centimeter høje, er placeret rundt omkring på RO’s Torv. De er skabt i blanksleben blå rønnegranit med håndhuggede motiver, der alle relaterer til stedets funktion som shoppingcenter, til placeringen i Roskilde, til hverdagen og familielivet hos dets brugere. Bænke som mødesteder, hvilesteder og til socialt samvær. Bænke får folk til at stoppe op og slappe af, tænke efter, snakke sammen. Urene symboliserer tiden, stressen – men her på bænken står tiden stille som urene i granitten. Avisernes logoer er danske, europæiske, amerikanske og arabiske – globaliseringen og det multikulturelle. Pengesedlen er en overdi-mensioneret 200-kroneseddel,der ved sin forstørrelse mister karakteren af enge og bliver til et billede. Børnetegningerne handler om familielivet, herunder ndkøbssituationen med indkøbsvognen. De er resultatet af en konkurrence udskrevet af Roskilde Avis om børne-tegninger og udvalgt af kunstneren efter personlighed, fantasi og liv. Tallerkenerne er musselmalede og repræsenterer, ligesom den broderede dug, bedste-forældrenes generation og festdagen, mens gaflerne er moderne hverdagsbestik med plastikskafter, der elimi-nerer ethvert tilløb til nostalgi. Fortolkningerne er helt frie og overlades til brugerne.";
        private const string HansPauli = "Hans Pauli Olsen(født 1957) er uddannet på Kunstakademiet i København under Willy Ørskov og Bjørn Nørgaard.Han debuterede allerede i 1974 i Thorshavn og fik sit gennembrud som kunstner på Charlottenborgs Efterårsudstilling i 1987. Han har haft talrige udstillinger og udsmykningsopgaver i både privat og offentlig regi.Hans Pauli Olsen er medlem af kunstnersammenslutningen Grønningen.";
        private const string AnnaKvinden = "ANNA er en nøgen kvindefigur i naturlig størrelse, støbt i bronze og anbragt på en sokkel af blå rønnegranit. Figuren står i en klassisk attitude med hænderne bag nakken og med blikket stolt rettet frem – ikke som i den klassiske skulptur med blikket rettet bly ned. Den er ikke glatsleben, men fremstår som direkte, rå afstøb-ning af den modellerede figur i ler, således at fremstil-lingsprocessen tydeligt aflæses og lader skulpturen fremstå som skulptur og som billede på en arbejds-proces. Soklen er i to lag, hvori der i det øverste, der rager ud over det nederste, er nedfældet en vandret liggende lille model af kvindefiguren. Fantasien sættes i sving, en anden historie fortælles, men det er op til beskueren selv at formulere den. KVINDEN PÅ BROEN består af to kvindefigurer i naturlig størrelse vendt med fødderne mod hinanden, idet den ene står retvendt på broen, mens den anden er op-hængt på hovedet i den øverstes forlængelse under broen. Et spejlbillede, en skygge, et drømmesyn, fysisk tilstedeværelse – som billede på noget uhåndgribeligt og imaginært. På spørgsmålet om, hvad han vil med sine to skulpturer af nøgne kvinder som udsmykning af RO’s Torv, svarer Hans Pauli Olsen, at han vil udsmykke – og hvad smykker mere end kvindekroppen? Den nøgne kvindekrop vil (i hvert fald for det mandlige blik) altid være forbundet med erotik, og udsmykningen tilfører således et erotisk element til det daglige indkøb. Et stilbrud, en udfor-dring, men også en pirring, voyeuristisk og exhibitio-nistisk, en provokation – som den berømte happening med Lene Adler Petersen skridende nøgen ned ad børstrappen for øjnene af de chokerede, stiligt jakkeklædte børsfolk. Men det er ikke det erotiske, der er kunstnerens ærinde. Kvindekroppen er jo, som skulpturelt motiv, klassisk og derfor egentlig neutral – en skulpturel form. Det er skulpturen og ikke kvinde-kroppen vi ser. Provokationen ligger snarere et andet sted – nemlig i at Hans Pauli Olsen som moderne billed-hugger tillader sig at arbejde naturalistisk og med et så klassisk fortærsket motiv.";
        private const string ChristellaBamford = "Christella Bamford (født 1961) er uddannet kunst-håndværker på linjen for keramik og glas på Kunst-håndværkerskolen i Kolding. Hun har siden 1991 arbejdet som selvstændig freelancedesigner, konsulent, kunsthåndværker og kunstner.";
        private const string TravlTrappe = "Idéen til udsmykningen, Den Travle Trappe, opstod da der var problemer med at få de besøgende på RO’s Torv til at opdage, at der overhovedet var en trappe i østenden af centret – alt for få mennesker brugte trappen. Det optimale ville være meget mere aktivitet på trappen – deraf idéen med de mange ben. At der både er sokkefødder og stilletben er naturligvis fordi, at det der venter for enden både er til hyggelige og festlige lejligheder. Spejlcylinderen, der i en evig strøm lader lyspletter vandre op af trinene, er tænkt som en magisk og eventyrlig hjælp, med det formål at vække nysgerrigheden og gøre rejsen op ad den stejle trappe lettere – som havde man medvind.";
        private const string JakobOgMichael = "JAKOB HUNOSØE (født 1975) er uddannet på Kunst-akademiet i København under Erik Steffensen og Henrik B. Andersen. Han debuterede på Charlottenborgs Forårsudstilling i 1997 og har siden haft en række udstillinger. MICHAEL FISCHER (født 1974) er uddannet på Kunst-akademiet i København under Claus Carstensen og Jesper Christiansen. Han debuterede på Charlotten-borgs Forårsudstilling 1998 og har siden haft en række udstillinger.";
        private const string BiografVæg = "Jakob Hunosøe og Michael Fischer har udsmykket RO’s Torvs biografkompleks med et 100 meter langt og 3 meter højt megaprint af en lystavle med matematiske strukturer i forskellige farver. Inspirationen til værket er Steven Spielbergs film fra 1977 “Nærkontakt af tredje grad” om menneskets møde med det ukendte, repræ-senteret af en livsform fra rummet. Menneskene forsøger i filmen at afkode de lyde de modtager fra rummet, og opnår en matematisk forståelse af dem som koordinater til et mødested. Til mødet konstrueres en lystavle, der omsætter lydene til et matematisk sprog i form af abstrakte kurver uden realitetsindhold. Man kommunikerer men ved ikke, hvad der kommunikeres. Lystavlen er således (ligesom Babelstårnet) et billede på sprogets afmagt og viljen til kommunikation. Kunstnerne fokuserer med deres værk på forholdet mellem afsen-der og modtager, mellem kunstværket og beskueren, hvor den egentlige kommunikation (som i filmen) er sprogløs, direkte, intuitiv. Budskabet forstås umid-delbart, hvis det er stærkt nok.";
        private const string JørnHansen = "Jørn Hansen (født 1944) er autodidakt billedhugger. Han har gennem tiden arbejdet både med maleri, tegning, assemblage og foto, men arbejder nu fortrins-vis med skulptur, installation og landart og med mange slags materialer – herunder især træ, glas, ler, granit og jern. Hans arbejde sprudler af fortælleglæde.";
        private const string Trærod = "Til ordet rod, den underjordiske del af en vækst, knytter sig mange bibetydninger. Noget oprindeligt som man har rod i, hvorfra ens rødder går eller som udgangspunkt for noget, et fundament, noget stillestående og sikkert, som man slår rod i eller som fanger én, når tiden går for langsomt, og man slår rødder. Alle disse betydninger slår én foran Jørn Hansens udsmykning på RO’s Torv. Med roden af et stort gammelt bøgetræ, har han bragt et stykke natur ind i shoppingcentret, hvor det udgør en stor kontrast til centrets arkitektur og indretning med dettes hovedsageligt lodrette og vandrette linjer. Træet har engang i formentlig anden halvdel af 1700-tallet slået rod i Ledreborg Slotspark under Christian Frederik, lensgreve af Holstein-Ledreborg, og har siden “mødt” hans efterkommere lige til Silvia Munro, født komtesse af Holstein-Ledreborg, inden det i vort århundrede blev væltet af en storm. Træet blev savet af og gravet fri med en rendegraver, og en 2 tons rod med jord blev transporteret til kunstnerens atelier, hvor jord og sten blev hakket ud og gravet af mellem gentagne tryk-spulinger, skåret i form, høvlet, fræset, pudset, poleret på afskårne flader og til sidst opsat på RO’s Torv. Her hviler roden på en glaskasse med indlagt lys, hvor tusindvis af skårne glasplader i et sært, organisk, reflekterende lysmønster genspejler rodens struktur, og placeringen op ad en spejlflade giver publikum mulighed for at se roden nedefra. En sidste repræsen-tant for stedets oprindelige natur og historie, fanget i en tidslomme, hvori den som en kæmpeblæksprutte desperat rækker ud efter sit eget spejlbillede eller forsøger at sprænge sine tidsmæssige rammer og række ind i nutiden. Et tankevækkende og associationsrigt fremmedelement, der dekorativt skaber rod i centrets velordnede kaos.";
        private const string KjeldUlrich = "Kjeld Ulrich (født 1942) blev uddannet på Det Fynske Kunstakademi under Kaj Kylborg 1968-72 og debuterede på Charlottenborgs Forårsudstilling i 1972. Han har haft talrige udstillinger siden både herhjemme og i ud-landet, og har udført en lang række udsmykninger. Han boede i Frankrig 1988-96 og igen 1998-2001, men har siden da boet her i landet.";
        private const string SkaktVæg = "Kjeld Ulrich har valgt at dække den 13 meter høje og 6 meter brede skaktvæg ved Trappe Øst med et stort fotoprint – udprintet i baner på lærred og efter opsæt-ningen bemalet af kunstneren. En lodret billedfrise i fire felter. Nederst en hvid stregtegning på sort bag-grund med stiliserede børnetegningsagtige figurer, et trekantet ansigt, en fugl vendt på hovedet og en kaktus. Valget af motiv og farve har her været påvirket af, at billedet her i bunden uundgåeligt vil blive skadet ved berøring. Over dette et billedfelt med et stiliseret landskab med bjerge og nøgne træer med et indsat konstruktivt element. Farverne er lyse grå og svagt gule. Herover et lidt større felt med et sort-hvidt fotografi fra en café i Paris med indlagte spejlelemen-ter og delvis overmalet med en stiliseret blomsterbuket i vase. Det øverste felt er domineret af en stregtegning i sort på hvid bund af et kvindekorset og nogle vandret-liggende vækster. Udsmykningens lidt kaotiske virvar af motiver genspejler i en collageagtig struktur shopping-centrets mangfoldighed af liv og vareudbud, dets blanding af hektisk travlhed og afslappet caféstemning, af handelsaktivitet og kultur – dets tilbud om at blande det nødvendige med det behagelige.";
        private const string LeifSylvester = "Leif Sylvester (født 1940) debuterede som billed-kunstner på Kunstnernes efterårsudstilling i 1969 og har siden haft talrige udstillinger – heriblandt i sit eget Galleri Python i København siden 1996. Men han er også kendt som skuespiller i flere film, som komponist, sce-nograf, tekstforfatter og for sit gadecirkus sammen med Erik Clausen.";
        private const string FotoStater = "Leif Sylvesters udsmykning af Trappe Vest er udført som digitaliseringer af kunstnerens malerier, mixet på computer og udprintet som store fotostater, hvoraf to på henholdsvis 6 x 8 meter og 3 x 8 meter er opsat på de to trappereposer ved udgangen til p-huset på hhv.første og tredje etage.Et tredje cirkelrundt billede, oprindelig beregnet til at sidde i loftet, er monteret på glas og placeret i det store, vestvendte vindue. Leif Sylvester er som altid folkelig, festlig og fornøjelig.Men måske ikke kun det.I hans billeder af mennesker og store katte i glade farver ligger eventyret, det uhøj-tidelige og dekorative til glæde for både voksne og børn og derfor meget velegnet et sted som RO’s Torv – yderligere tilpasset miljøet med stiliserede højhuse og konstruktive elementer.Men der kan samtidig være en egen melankoli over hans billeder, en forundring og noget tænksomt i figurernes øjne med appel til især voksne.Noget der gør, at vi ikke straks slipper dem, men måske betyder, at vi har mere med hjem fra centret, end det vi har betalt for i butikkerne";
        private const string AndrzejLemiszewski = "Andrzej Lemiszewski (født 1952 i Polen) er dansk statsborger og bosat i Danmark siden 1971, uddannet på Kunstakademiet i København og bor og arbejder hen-holdsvis i Pietrasanta i Italien og i København. Han har haft talrige udstillinger i Danmark og udlandet, har udført en lang række udsmykninger i både privat og offentlig regi, har modtaget flere priser i ind- og udland og er repræsenteret i offentlige og private samlinger i Europa og USA.";
        private const string HelgesKilde = "Det er en yderst vanskelig opgave Andrzej Lemiszewski har løst med udsmykning af blindtarmen ved rulle-trapperne med vandkunsten Helges Kilde. Ad fire vandtrapper af patineret bronze løber vandet ud i et bassin, der, ligesom rummets vægge, er beklædt med grå cardozosten. Den ene trappe løber fra væggens overkant direkte ned i bassinet, hvor vandet stille siver ud, mens to andre hænger på de tilstødende vægge og slutter blindt ca. 30 centimeter oppe, hvorfra vandet løber plaskende ned i bassinet. En fjerde trappe er en fritstående kegleform, hvorfra vandet boblende ud fra toppen rinder ned. Området er udpræget et gennem-gangssted, hvor publikum iler forbi på vej rundt i centret, og det er denne karakter af passage som kunstneren på én gang spiller op til og bryder med sit værk. Som en fontæne i en storby er det med vandets stadige, rastløse strømmen og flimrende lysreflekser et billede på beskuerens egen situation – samtidig med, at det med naturstenene, trappernes grønne farve og vandets rislen giver associationer til kilder i bjergene, og med vandets uendelige kredsløb, dets stille rislen, klukken, plasken og boblen kalder på afslappet kontemplation.";
        private const string BjørnPoulsen = "Bjørn Poulsen (født 1959) er uddannet fra 1979-81 på Billedskolen på Lolland og fra 1981-88 på Kunstaka-demiet i København under Willy Ørskov og Bjørn Nørgaard. Han har haft talrige udstillinger både separat og i grupper, har modtaget legater fra Statens Kunst-fond og har udført flere private og offentlige udsmyk-ningsopgaver. Bjørn Poulsen er medlem af kunstner-sammenslutningen Grønningen.";
        private const string StoreBjørn = "Bjørn Poulsens værk, Storebjørn, en stjerneagtig skulptur i et væld af farver ophængt under loftet, rummer en række paradokser. Denne skulptur er skabt som håndarbejde af kunstneren selv i atalieret, men af industrielt fremstillede materialer og produkter – plastikspande og indkøbskurve. Overskuds- og forbrugssamfundets masseproduktion omsat til kunst. I sine mange sammensnittede lag har skulpturen en samlende og tæt pakket massiv tyngde, der modsat ophæves ved ophængningen af de dynamisk strittende udløb mod rummet. Den kan opleves som farlig og destruktiv, som en eksplosion af energi, aggressivt strittende som en mine eller som en skæv stjerne, en svævende blæksprutte fra Flemming Quist Møllers “Bennys Badekar”, et sprudlende festfyrværkeri. Fantasi og leg.";
        private const string SteffenTast = "Steffen Tast (født 1951) er som billedkunstner auto-didakt. Han har en lang række udstillinger bag sig, har udført mange udsmykninger både i offentlig og privat regi, har modtaget en lang række legater og er repræ-senteret i mange offentlige og private samlinger i ind- og udland. Steffen Tast er medlem af kunstner-sammenslutningen Den Gyldne.";
        private const string MizarGalakse = "MIZAR, der er navnet på en stjerne, som set fra jorden virker ovalformet, er en ophængt flad, ægformet mobile. Den består af 403 nedhængende strimler af aluminium og acryl med endestrålende lysfibre, hvor lysintensiteten øges mod mobilens spids. Acrylstyk-kerne fanger lyset i kanterne og giver det liv. GALAKSE er en installation bestående af cirka 1.600 stykker glas ophængt i et skråt plan i en koboltblå kuppel med nogle lysende “stjerner” over området ved rulletrapperne. Dens centrale del består af yderligere 81 endestrålende lysfibre og bly, der får lyset til at stå og pulsere. ANDROMEDAS SLØR er ophængt over Halfdans Kilde og består af 1.920 lysfibre hængende fra et nedsænket loft af aluminium, der samtidig markerer afgrænsningen af et lille torv. Installationerne er alle mobiler, hvis dele bliver sat i bevægelse af de luftstrømme, der opstår ved publikums bevægelser i rummene og ved f.eks. døres åbning og lukning. Lyset og bevægelserne er i sig selv et fasci-nerende og oplevelsesrigt element i shoppingcentrets store rum samtidig med, at associationerne til siv, der svajer i vinden, og til stjernehimlen er nærliggende som metaforer for naturen og det landlige, det nære og oprindelige – til livet og universet udenfor centret.";
        private const string ChistellaHelgeDavid = "CHRISTELLA BAMFORD (født 1961) er uddannet kunst-håndværker på linjen for keramik og glas på Kunsthånd-værkerskolen i Kolding. Hun har siden 1991 arbejdet som selvstændig freelancedesigner, konsulent, kunst-håndværker og kunstner. HELGE NORDSTRØM (født 1963) er autodidakt billed-kunstner med baggrund i 80’ernes eksperimenterende musik- og teaterscene og har en bachelorgrad med speciale i kunstpædagogik. DAVID LEWIS (født 1960 i Canada) lever og arbejder i Danmark på værkstedet The Other Place Studios i Hvalsø. Han er uddannet fra Cardiff College of Art and Design samt Darlington College of the Arts i Stor-brittanien. Han arbejder både med illustration, scenografi og billedkunst og har undervist på Danmarks Designskole.";
        private const string DeSkønnePorte = "Parkeringshuset er udsmykket af tre kunstnere, Christella Bamford, Helge Nordstrøm og David Lewis, med billeder printet ud på plastfolie. Om det fælles koncept, De Skønne Porte, fortæller de, at udsmyk-ningen af parkeringshuset er båret af grundtanken om, at den enkelte etages udsmykkede vægflade og indgang til RO’s Torv fremstår som en port, hvor tilrejsende møder centret – en visuel port ind til en bestemt type oplevelser og muligheder. De tre kunstnere har givet deres bud i en sammenhængende idé, hvor hver etage har sin egen grundfarve og tematiske udgangspunkt. Det handler om basale menneskelige foreteelser, ud-foldelsesmuligheder og identitet. RØD – PASSIONEN (P-2) Her har kunstneren og design-eren Christella Bamford behandlet de fotografiske samplinger digitalt i et forsøg på at fange nogle af livets små og store mirakler, der kan få passionen til at krydre hverdagen i et spænd mellem himmellegemer og mole-kyler. Ud over sit bidrag med udsmykningen af dette kunstværk har Christella Bamford stået for det udvik-lingsmæssige og afsluttende designarbejde på De Skønne Porte. ORANGE – REJSEN (P-1) Med et naivt billedsprog har Helge Nordstrøm her skabt en fortælling om menneske-hedens evolutionelle udvikling, dets stræben og udfor-skertrang i en serie malerier om forskellige historiske og kulturelle begivenheder fra vikingerejser til Ikaros på hjemmelavet propelcykel. GUL – FORVANDLINGEN (P0) Illustratoren og billed-kunstneren David Lewis har her frembragt en serie grafiske billeder, inspireret af temaet forvandlingen, med associa-tioner som bevægelse, valg og håb mani-festeret i billeder med nogle klare og enkle visuelle historier, afbalanceret med et element af ironi og humor, der opfordrer beskueren til at kigge en ekstra gang – gerne med et smil på læben. GRØN – DRØMMEN (P1) I en kombination af et eks-pressivt og et figurativt billedsprog har Helge Nord-strøm forholdt sig til farven grøn som drømmenes og følelsernes farve. Hans store billedserie er bygget op over naturmotiver med haven som bærende element. Vestsiden er holdt i lysere nuancer, hvorimod østsiden udtrykker mere farvekraft. Her er mulighed for at finde alt fra engle til kronhjorte og elefanter i forskellige bud på, hvad drømme kan indeholde og betyde. Drømmen er vores mulighed for at opnå det umulige. BLÅ – MØDET (P2) David Lewis har valgt at undersøge begreber, som associerer til temaet mødet, såsom dialog, forventninger og opdagelse, og har herover skabt en serie fortællende billeder, der illustrerer en families ankomst – en mor, en far og to børn ved ind-gangen til shoppingcenteret, alle fire fulde af forvent-ning til hvilke overraskelser og fornøjelser, der venter dem bagved de glidende skydedøre. VIOLET – VISIONEN (P3) Åbning mod stjernerne – etagen er ikke udsmykket.";
        #endregion

        #region Instansfelter 
        private ObservableCollection<Kunst> _kunstværkerne;
        private Kunst _valgtKunstværket;
        #endregion

        #region properties
        public Kunst ValgtKunstværket
        {
            get { return _valgtKunstværket; }
            set
            {
                _valgtKunstværket = value;
                OnPropertyChanged();
            }
        }

        public ObservableCollection<Kunst> Kunstværkerne
        {
            get { return _kunstværkerne; }
        }
        #endregion

        #region Konstruktør
        public KunstværkerViewModel()
        {
            _kunstværkerne = new ObservableCollection<Kunst>();

            Kunstværkerne.Add(new Kunst("Granitbænke", "Laila Westergaard", Laila, "Rundt i hele centeret", GranitBænke, "../Assets/Granitbænke.jpg"));
            Kunstværkerne.Add(new Kunst("Anna og kvinden på broen", "Hans Pauli Olsen", HansPauli, "Ved rulletrappe til information?", AnnaKvinden, "../Assets/AnnaKvinden.jpg"));
            Kunstværkerne.Add(new Kunst("Den Travle Trappe", "Christella Bamford", ChristellaBamford, "??", TravlTrappe, "../Assets/TravleTrappe.jpg"));
            Kunstværkerne.Add(new Kunst("Biografvæg", "Jackob Hunosøe og Michael Fischer", JakobOgMichael, "??", BiografVæg, "../Assets/Biografvæg.jpg"));
            Kunstværkerne.Add(new Kunst("Trærod", "Jørn Hansen", JørnHansen, "??", Trærod, "../Assets/Træroden.jpg"));
            Kunstværkerne.Add(new Kunst("Skaktvæg", "Kjeld Ulrich", KjeldUlrich, "Ved trappe Øst", SkaktVæg, "../Assets/Skaktvæg.jpg"));
            Kunstværkerne.Add(new Kunst("Fotostater", "Leif Sylvester", LeifSylvester, "Trappe Vest", FotoStater, "../Assets/Fotostater.jpg"));
            Kunstværkerne.Add(new Kunst("Helges Kilde", "AndrzejLemiszewski", AndrzejLemiszewski, "Ved rulletrapper", HelgesKilde, "../Assets/HelgesKilde.jpg"));
            Kunstværkerne.Add(new Kunst("Store bjørn", "Bjørn Poulsen", BjørnPoulsen, "??", StoreBjørn, "../Assets/Storebjørn.jpg"));
            Kunstværkerne.Add(new Kunst("Mizar, galakse og andromedas slør", "Steffen Tast", SteffenTast, "??", MizarGalakse, "../Assets/Mizar.jpg"));
            Kunstværkerne.Add(new Kunst("De skønne porte", "Christella Bamford, Helge Nordstrøm og David Lewis", ChistellaHelgeDavid, "Parkering", DeSkønnePorte, "../Assets/DeSkønnePorte.jpg"));

            _valgtKunstværket = new Kunst();
        }
        #endregion

        #region OnPropertyChanged
        protected virtual void OnPropertyChanged
        ([CallerMemberName] string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }

        public event PropertyChangedEventHandler PropertyChanged;
        #endregion
    }
}
